name: "caller"
on:
  push:
    branches:
      - "main"

jobs:
  caller:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ["dir1", "dir2"]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "call called.yaml"
        uses: ./.github/workflows/called.yaml
