name: called

on:
  workflow_call:

jobs:
  called:
    runs-on: ubuntu-latest
    steps:
      # - name: "Checkout"
      #   uses: actions/checkout@main

      - name: Reuse test
        run: echo "reuse succeeded!"