name: called

on:
  workflow_call:

jobs:
  called:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ["dir1", "dir2"]
    steps:
      - name: "Checkout"
        uses: actions/checkout@main

      - name: Reuse test
        run: echo "dir is ${{ matrix.dir }}"