name: "caller"
on:
  push:
    branches:
      - "main"

jobs:
  caller:
    strategy:
      matrix:
        val: "value"

    steps:
      - name: "call called.yaml"
        uses: ./.github/workflows/called.yaml
