name: "caller"
on:
  push:
    branches:
      - "main"

jobs:
  caller:
    strategy:
      matrix:
        dir: ["dir1", "dir2"]

    steps:
      - name: "call called.yaml"
        uses: ./.github/workflows/called.yaml
